version: '3.7'
services:
  nats-admin:
    container_name: nats-admin
    build: 
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/client/src
      - ./client/package.json:/client/package.json
      - ./client/.env:/client/.env
      - /node_modules
    stdin_open: true
    tty: true